# Generated by Django 4.1.2 on 2023-02-03 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('Case_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Case_Name', models.CharField(max_length=50, verbose_name='Название кейса')),
                ('Case_Comment', models.TextField(verbose_name='Коментарий')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('Section_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Section_Name', models.CharField(max_length=100, verbose_name='Название раздела')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
            options={
                'verbose_name': 'Раздел кейса',
                'verbose_name_plural': 'Разделы кейса',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('Period_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Period_Name', models.CharField(max_length=100, verbose_name='Период')),
                ('Period_Sort', models.FloatField(default=models.AutoField(primary_key=True, serialize=False), null=True, verbose_name='Вес при сортировке')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Периоды',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('Parameter_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Parameter_Name', models.CharField(max_length=100, verbose_name='Название')),
                ('Parameter_Comment', models.TextField(verbose_name='Коментарий')),
                ('Parameter_Sort', models.FloatField(default=models.AutoField(primary_key=True, serialize=False), null=True, verbose_name='Вес при сортировке')),
                ('section', models.ManyToManyField(to='cases.section')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('Data_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Data_Value', models.FloatField(default=0, null=True, verbose_name='Значение')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.parameter')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.period')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения',
            },
        ),
    ]
