# Generated by Django 4.1.2 on 2023-02-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='Parameter_Var_Name',
            field=models.CharField(default='V<django.db.models.fields.AutoField>', max_length=10, verbose_name='Название переменной'),
        ),
    ]
