# Generated by Django 4.1.2 on 2023-02-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_parameter_parameter_var_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='Parameter_Var_Name',
            field=models.CharField(default=0, max_length=10, verbose_name='Название переменной'),
        ),
    ]
