# Generated by Django 4.1.2 on 2023-03-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/product_images/'),
        ),
    ]
